apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ws
  name: ws
spec:
  replicas: {{ .Values.ws.replicas | default 1 }}
  selector:
    matchLabels:
      app: ws
  template:
    metadata:
      labels:
        app: ws
    spec:
      automountServiceAccountToken: false
      containers:
      - image: registry.gitlab.com/web-hook/ws:{{ .Values.ws.tag }}
        name: ws
        imagePullPolicy: Always
        resources:
          requests:
            memory: 64Mi
            cpu: 100m
          limits:
            memory: 64Mi 
            cpu: 100m
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          runAsUser: 10000
          seccompProfile:
            type: RuntimeDefault
          capabilities:
            drop:
            - ALL
      restartPolicy: Always
