apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mongo
  name: mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      automountServiceAccountToken: false
      containers:
      - image: mongo:{{ .Values.mongo.tag }}
        name: mongo
        resources:
          requests:
            memory: 256Mi
            cpu: 200m
          limits:
            memory: 256Mi 
            cpu: 200m
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          seccompProfile:
            type: RuntimeDefault
          capabilities:
            drop:
            - ALL
            add:
            - CHOWN
            - DAC_OVERRIDE
            - SETGID
            - SETUID
        volumeMounts:
        - name: data
          mountPath: /data/db
        - name: tmp
          mountPath: /tmp
      volumes:
      - name: data
        emptyDir: {}
      - name: tmp
        emptyDir: {}