apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: www
  name: www
spec:
  replicas: {{ .Values.www.replicas | default 1 }}
  selector:
    matchLabels:
      app: www
  template:
    metadata:
      labels:
        app: www
    spec:
      automountServiceAccountToken: false
      containers:
      - image: registry.gitlab.com/web-hook/www:{{ .Values.www.tag }}
        name: www
        imagePullPolicy: Always
        resources:
          requests:
            memory: 256Mi
            cpu: 100m
          limits:
            memory: 256Mi 
            cpu: 100m
        securityContext:
          allowPrivilegeEscalation: false
          # readOnlyRootFilesystem: true
          runAsUser: 10000
          seccompProfile:
            type: RuntimeDefault
          capabilities:
            drop:
            - ALL
      restartPolicy: Always
