configs:
  repositories:
    config-repo:
      url: https://gitlab.com/web-hook/config.git
      name: webhooks
      type: git

extraObjects:
- apiVersion: argoproj.io/v1alpha1
  kind: Application
  metadata:
    name: webhooks
    namespace: argo
  spec:
    project: default
    source:
      repoURL: https://gitlab.com/web-hook/config.git
      targetRevision: main
      path: apps/webhooks
      helm:
        releaseName: webhooks
        valueFiles:
          - "values.yaml"
    destination:
      server: https://kubernetes.default.svc
      namespace: webhooks
    syncPolicy:
      automated: {}
      syncOptions:
        - CreateNamespace=true
