repositories:
  - name: traefik
    url: https://helm.traefik.io/traefik

releases:
  - name: traefik
    namespace: traefik
    labels:
      app: traefik
    chart: traefik/traefik
    version: ~10.24.1
    values:
      - ./values.yaml.gotmpl
